M48
; DRILL file {KiCad 9.0.2} date 2025-06-17T13:17:30+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-17T13:17:30+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X124.612Y-83.825
X124.612Y-121.107
X164.95Y-83.825
X165.227Y-121.26
M30
